### ISSUE TITLE
Templates should use `punctuation.section.template`

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/YamlPipelines#16]
The interpolation punctuation in the following snippet receives the scope `meta.string.yaml string.unquoted.plain.out.yaml punctuation.section.block.begin.pipeline`, however according to the [guidelines](https://www.sublimetext.com/docs/scope_naming.html) it should be `punctuation.section.interpolation.{begin,end}` (which I have a color scheme rule for).

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/.vitepress/dist
          cname: docs.sublimetext.io
```
