### ISSUE TITLE
Handle GitLab's `!reference` custom tag

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/YamlPipelines#18]
Gitlab supports referencing other realized parts of a pipeline even from different imported files using a special `!reference` tag. While this is technically allowed everywhere, for YamlPipelines it is most relevant in the script blocks to build up script blocks from multiple sources.

Documentation: https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags

Example (from the documentation):

```yaml
include:
  - local: setup.yml

.teardown:
  after_script:
    - echo deleting environment

test:
  script:
    - !reference [.setup, script]
    - echo running my own command
  after_script:
    - !reference [.teardown, after_script]
```

Currently, these tags are parsed fine but the list contents are interpreted as shell function calls:

![2024-04-26_18-21-59](https://github.com/SublimeText/YamlPipelines/assets/931051/e126039a-0e25-42ba-a67b-128799d67c9a)
