### ISSUE TITLE
Colon in GitLab script block exits shell embed

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/YamlPipelines#30]
```yaml
renovate:
  timeout: 2h
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  artifacts:
    when: always
    expire_in: 7d
    paths:
      - '$RENOVATE_LOG_FILE'
      - renovate\cache\others\npm\_logs
  script:
    - 'echo "\$RENOVATE_EXTRA_FLAGS: $RENOVATE_EXTRA_FLAGS"'
    - renovate $RENOVATE_EXTRA_FLAGS
```

minimal:
```yaml
renovate:
  script:
    - 'echo "\$RENOVATE_EXTRA_FLAGS: $RENOVATE_EXTRA_FLAGS"'
```

![Image](https://github.com/user-attachments/assets/8d840ff3-0d7b-413c-88d8-32db424969ea)
