### ISSUE TITLE
GitHub special var content

### ISSUE THREAD

**Issue by michaelblyons** [SublimeText/YamlPipelines#4]
In GitHub Actions, add 

```yaml
  inside-variable-reference:
    - meta_append: true
    - match: \bmatrix\b
      scope: constant.language.pipeline
    - match: \.
      scope: punctuation.accessor.dot.pipeline
```
