### ISSUE TITLE
Gitlab: Support YAML anchor references in script list blocks

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/YamlPipelines#8]
In Gitlab pipelines, YAML anchors are supported and also for the script list (which is flattened by default). Example job definition:

```yml
.npm-deploy-gitlab:
  extends: .npm-deploy-job
  before_script:
    - *set-gitlab-token
    - *setup-node-modules
    - *setup-gitlab-registry
  script:
    - npm publish --registry "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
```
