### ISSUE TITLE
Gitlab: label scoping is inaccurate

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/YamlPipelines#9]
For the following job definition, several keys are scoped as `entity.name.label` but there is no reason for them to be.
```yml
.npm-test:
  extends: .npm-test-job
  artifacts:
    when: always
    reports:
      junit: "**/reports/**/*.xml"
    paths:
      - coverage
      - reports
  script:
    - npm run test
```

![2023-07-12_15-12-37](https://github.com/SublimeText/YamlPipelines/assets/931051/f1e9f823-8dc5-49cf-8275-583db9dbd26c)

I suppose the intention was to highlight & index job names, i.e. `.npm-test`, which are always top-level keys for Gitlab pipelines. The may also start with a period to indicate them not being used by default but still extendable (using `extends`), which is currently not matched.
